http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    readtimeout: "30000"
    
db:
  host: "b3m2fhmi2a041caf2fnw-mysql.services.clever-cloud.com"
  port: "3306"
  username: "u6nmmhnyn7b8p7tb"
  password: "![l2tssU12jwWj8a6Qd6ZQ8JchvgThnEzL]"  
  database: "b3m2fhmi2a041caf2fnw"
  

