#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        type: !include ../datatype/error-response-dataType.raml
        example: !include ../examples/error-response-400-example.json
  401:
    body:
      application/json:
        type: !include ../datatype/error-response-dataType.raml
        example: !include ../examples/error-response-401-example.json
  404:
    body:
      application/json:
        type: !include ../datatype/error-response-dataType.raml
        example: !include ../examples/error-response-404-example.json   
  500:
    body:
      application/json:
        type: !include ../examples/error-response-500-example.json
        example: !include ../examples/error-response-500-example.json
                 
                                                      
    